try{
	console.log(x);
}catch(err){
	console.log("\n");
	console.log(err);
	console.log("\n");
}finally{
	console.log("Hello world");
}
